language: cpp
git:
  submodules: false
before_install:
    - sudo apt-get update -y
    - sudo apt-get install cmake gcc gfortran python clang -y
before_script:
  - FC=gfortran
env:
  global:
    - PROJECT_ROOT="$(pwd)"
    - CI_SCRIPTS="$PROJECT_ROOT/.ci"
  matrix:
    - CI_TARGET=gcc-debug-coverage
    - CI_TARGET=gcc-release
    - CI_TARGET=gcc-debug-i8
    - CI_TARGET=clang-debug
    - CI_TARGET=clang-release
script:
  - bash "${CI_SCRIPTS}/${CI_TARGET}.sh"
notifications:
  recipients:
    - roberto.d.remigio@uit.no
    - luca.frediani@uit.no
  email:
    on_success: change
    on_failure: always
