language: cpp
git:
  submodules: false
before_install:
    - sudo apt-get update -y
    - sudo apt-get install cmake gcc gfortran python clang -y
before_script:
  - FC=gfortran
script:
  - python setup --cxx=g++ --cc=gcc --fc=gfortran --type=debug --tests
  - cd build
  - make
  - ctest
notifications:
  recipients:
    - roberto.d.remigio@uit.no
    - luca.frediani@uit.no
  email:
    on_success: change
    on_failure: always
